---
- name: Upload platziverse-fixis files
  copy: 
    dest=/usr/local/src
    src=platziverse-fixis
    mode=u=rwx,g=rwx,o=rx
- name: Install node modules
  command: npm install
    chdir=/usr/local/src/platziverse-fixis
    creates=/usr/local/src/platziverse-fixis/node_modules