---
- name: Upload platziverse-agent
  copy:
    src=platziverse-agent
    dest=/usr/local/src
    mode=u=rwx,g=rwx,o=rx
- name: Install node modules
  command: npm install
    chdir=/usr/local/src/platziverse-agent
    creates=/usr/local/src/platziverse-agent/node_modules