---

- name: Download the script
  get_url:
    url=https://deb.nodesource.com/setup_8.x
    dest=/tmp/install_node_8.sh
    mode=u=rwx,g=rwx,o=rx
- name: Run the script
  command: /tmp/install_node_8.sh
    creates=/etc/apt/sources.list.d/nodesource_8.list
- name: Installing node
  apt:
    update_cache=yes
    state=latest
    name=nodejs