---
- name: Upload platziverse-api
  copy:
    src=platziverse-api
    dest=/usr/local/src
    mode=u=rwx,g=rwx,o=rx
- name: Install node modules
  command: npm install
    chdir=/usr/local/src/platziverse-api
    creates=/usr/local/src/platziverse-api/node_modules
- name: Upload script
  copy:
    src=platziverse-api.service
    dest=/lib/systemd/system
    mode=u=rwx,g=rwx,o=rx
- name: Upload config
  copy:
    src=platziverse-api.config
    dest=/etc/nginx/sites-enabled
    mode=u=rwx,g=rwx,o=rx
- name: Run script
  service:
    name=platziverse-api
    state=restarted
    enabled=yes
- name: Run config nginx
  service:
    name=nginx
    state=reloaded