---
- include: deps.yml
- name: Upload platziverse-mqtt
  copy:
    dest=/usr/local/src
    src=platziverse-mqtt
    mode=u=rwx,g=rwx,o=rx
- name: Install node modules
  command: npm install
    chdir=/usr/local/src/platziverse-mqtt
    creates=/usr/local/src/platziverse-mqtt/node_modules
- name: Upload service script
  copy:
    dest=/lib/systemd/system
    src=platziverse-mqtt.service
    mode=u=rwx,g=rwx,o=rx
- name: Run service script
  service:
    name=platziverse-mqtt
    state=restarted
    enabled=yes